server:
    port: 8081

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/notes_dev?characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true
        username: root
        password:
        driver-class-name: com.mysql.cj.jdbc.Driver
#
#mybatis-plus:
#    mapper-locations: classpath:mappers/*.xml
mybatis:
    type-aliases-package: com.example.webtest.model
    mapper-locations: classpath:/mappers/*.xml
    configuration:
        mapUnderscoreToCamelCase: true